### ISSUE TITLE
Headings need to be adjusted on catalogue page

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#31]
How to structure:

(h1) Open Data Catalogue
- (h2) Data catalogue
-- (h3) One Address Repository (OAR)
-- (h3) Toronto Centreline (TCL)
-- (h3) One-Way Streets 
- (h2) Sidebar
-- (h3) Type
-- (h3) Topic
-- (h3) Division
-- (h3) Format

**Comment by sidramatik** [comment]
`<div role="main" aria-labelledby="foo">
   <h1 id="foo">Wild fires spread across the San Diego Hills</h1>
   Strong winds expand fires ignited by high temperatures ...
</div>`

**Comment by sidramatik** [comment]
```
<div role="main" aria-labelledby="foo">
   <h1 id="foo">Wild fires spread across the San Diego Hills</h1>
   Strong winds expand fires ignited by high temperatures ...
</div>
```

**Comment by careduz** [comment]
Made the following changes:
- sidebar filter headings (e.g. Topic) --> h3
- dataset title (e.g. One-Way Streets) --> h3

Did not see the H2 titles mentioned above (i.e. Data catalogue, Sidebar) and we aren't clear how to apply the example above. Could you take care of the rest? otherwise, happy to tackle it after more specifics.

**Comment by sidramatik** [comment]
Include the H2 titles as sr-only. I can include these. Good work otherwise!

**Comment by sidramatik** [comment]
Resolved :)
